# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEksiSozlukLoginTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eksiSozlukLoginTest(self):
    self.driver.get("https://localhost:44382/Register/Index")
    self.driver.set_window_size(1550, 830)
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "Name")))
    self.driver.find_element(By.NAME, "Name").send_keys("Selami")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "Surname")))
    self.driver.find_element(By.NAME, "Surname").send_keys("Zımba")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "City")))
    self.driver.find_element(By.NAME, "City").send_keys("Niğde")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "Email")))
    self.driver.find_element(By.NAME, "Email").send_keys("hus")
    self.driver.find_element(By.NAME, "Email").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "Email").send_keys("huseyinaydin99@gmail.com")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "Username")))
    self.driver.find_element(By.NAME, "Username").send_keys("zimba99")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "Password")))
    self.driver.find_element(By.NAME, "Password").send_keys("123456Aa*")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.NAME, "ConfirmPassword")))
    self.driver.find_element(By.NAME, "ConfirmPassword").send_keys("123456Aa*")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn:nth-child(22)")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(22)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "UserName")))
    self.driver.find_element(By.NAME, "UserName").send_keys("zimba99")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "ConfirmCode")))
    self.driver.find_element(By.NAME, "ConfirmCode").send_keys("780606")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "div:nth-child(5) > .btn")))
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > .btn").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "UserName")))
    self.driver.find_element(By.NAME, "UserName").send_keys("zimba99")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "Password")))
    self.driver.find_element(By.NAME, "Password").send_keys("123456Aa*")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn:nth-child(6)")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(6)").click()
  
